// <auto-generated />
using System;
using Appointments.Records;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace appointments.Migrations
{
    [DbContext(typeof(Pgres))]
    [Migration("20190329211038_schedule_appointment")]
    partial class schedule_appointment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Appointments.Features.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int>("MinuteDuration");

                    b.Property<long>("ScheduleId");

                    b.Property<long>("Start");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScheduleId", "Start");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Appointments.Features.Participant", b =>
                {
                    b.Property<long>("AppointmentId");

                    b.Property<string>("SubjectId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("AppointmentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("Appointments.Features.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<Guid>("PrincipalId");

                    b.HasKey("Id");

                    b.HasAlternateKey("PrincipalId", "Name");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Appointments.Features.Appointment", b =>
                {
                    b.HasOne("Appointments.Features.Schedule")
                        .WithMany("Appointments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Appointments.Features.Participant", b =>
                {
                    b.HasOne("Appointments.Features.Appointment", "Appointment")
                        .WithMany("Participants")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
