// <auto-generated />
using System;
using Appointments.Records;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace appointments.Migrations
{
    [DbContext(typeof(Pgres))]
    [Migration("20190402222717_Schedules")]
    partial class Schedules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Appointments.Domain.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int>("Duration");

                    b.Property<string>("ScheduleName")
                        .IsRequired();

                    b.Property<long>("Start");

                    b.HasKey("Id");

                    b.HasAlternateKey("ScheduleName", "Start");

                    b.HasIndex("Start");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Appointments.Domain.Participant", b =>
                {
                    b.Property<long>("AppointmentId");

                    b.Property<string>("SubjectId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("AppointmentId", "SubjectId");

                    b.HasIndex("Name");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("Appointments.Domain.Schedule", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256);

                    b.Property<Guid>("PrincipalId");

                    b.HasKey("Name");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Appointments.Domain.Appointment", b =>
                {
                    b.HasOne("Appointments.Domain.Schedule", "Schedule")
                        .WithMany("Appointments")
                        .HasForeignKey("ScheduleName")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Appointments.Domain.Participant", b =>
                {
                    b.HasOne("Appointments.Domain.Appointment", "Appointment")
                        .WithMany("Participants")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
